// <auto-generated />
using System;
using ClinicNow.Services.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicNow.Services.Database.Migrations
{
    [DbContext(typeof(ClinicNowContext))]
    [Migration("20260825185757_AddNotificationsAndNews")]
    partial class AddNotificationsAndNews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MedicalServiceId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReminderSentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MedicalServiceId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            DoctorId = 1,
                            EndUtc = new DateTime(2026, 8, 18, 9, 30, 0, 0, DateTimeKind.Utc),
                            LocationId = 1,
                            MedicalServiceId = 1,
                            PatientId = 1,
                            StartUtc = new DateTime(2026, 8, 18, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            CancellationReason = "Pacijent se razbolio.",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            DoctorId = 1,
                            EndUtc = new DateTime(2026, 8, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            LocationId = 1,
                            MedicalServiceId = 2,
                            PatientId = 2,
                            StartUtc = new DateTime(2026, 8, 20, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 4,
                            DoctorId = 2,
                            EndUtc = new DateTime(2026, 8, 26, 9, 45, 0, 0, DateTimeKind.Utc),
                            LocationId = 2,
                            MedicalServiceId = 5,
                            PatientId = 1,
                            StartUtc = new DateTime(2026, 8, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 2,
                            DoctorId = 1,
                            EndUtc = new DateTime(2026, 8, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            LocationId = 1,
                            MedicalServiceId = 1,
                            PatientId = 2,
                            StartUtc = new DateTime(2026, 8, 27, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 4,
                            DoctorId = 2,
                            EndUtc = new DateTime(2026, 9, 2, 11, 15, 0, 0, DateTimeKind.Utc),
                            LocationId = 2,
                            MedicalServiceId = 4,
                            PatientId = 1,
                            StartUtc = new DateTime(2026, 9, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.AppointmentAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActingUserId")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActingUserId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("AppointmentAuditLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActingUserId = 2,
                            AppointmentId = 1,
                            Description = "Termin završen.",
                            OccurredAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            ActingUserId = 2,
                            AppointmentId = 2,
                            Description = "Pacijent se razbolio.",
                            OccurredAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            ActingUserId = 4,
                            AppointmentId = 3,
                            Description = "Termin potvrđen.",
                            OccurredAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            ActingUserId = 2,
                            AppointmentId = 4,
                            Description = "Termin zakazan.",
                            OccurredAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            ActingUserId = 4,
                            AppointmentId = 5,
                            Description = "Termin zakazan.",
                            OccurredAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mostar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tuzla"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Zenica"
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Doktor opće medicine sa 10 godina iskustva.",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseNumber = "LKB-10023",
                            LocationId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Specijalista kardiologije.",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseNumber = "LKB-10087",
                            LocationId = 2,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.DoctorSpecialization", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("DoctorSpecializations");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            SpecializationId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            SpecializationId = 4
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ferhadija 12",
                            CityId = 1,
                            Name = "Poliklinika Centar"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bulevar narodne revolucije 5",
                            CityId = 2,
                            Name = "Poliklinika Sunce"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Slatina 3",
                            CityId = 3,
                            Name = "Poliklinika Zdravlje"
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.MedicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MedicalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Osnovni ljekarski pregled.",
                            DurationMinutes = 30,
                            Name = "Opći pregled",
                            Price = 50.00m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pregled kod dermatologa.",
                            DurationMinutes = 30,
                            Name = "Dermatološki pregled",
                            Price = 80.00m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Ultrazvučni pregled.",
                            DurationMinutes = 20,
                            Name = "Ultrazvuk",
                            Price = 60.00m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Osnovne laboratorijske pretrage krvi.",
                            DurationMinutes = 15,
                            Name = "Laboratorijske analize",
                            Price = 40.00m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pregled kod kardiologa.",
                            DurationMinutes = 45,
                            Name = "Kardiološki pregled",
                            Price = 90.00m
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 8, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            ImageContentType = "image/png",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 100, 248, 15, 0, 1, 5, 1, 1, 39, 24, 227, 102, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            Text = "Poliklinika Sunce proširuje radno vrijeme kardiologije od 1. septembra.",
                            Title = "Nove ordinacije od septembra"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 8, 20, 12, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Sada možete zakazati termin direktno iz mobilne aplikacije, bez poziva.",
                            Title = "Online zakazivanje termina"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 8, 23, 15, 0, 0, 0, DateTimeKind.Utc),
                            ImageContentType = "image/png",
                            ImageData = new byte[] { 137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 1, 0, 0, 0, 1, 8, 4, 0, 0, 0, 181, 28, 12, 2, 0, 0, 0, 11, 73, 68, 65, 84, 120, 218, 99, 100, 248, 15, 0, 1, 5, 1, 1, 39, 24, 227, 102, 0, 0, 0, 0, 73, 69, 78, 68, 174, 66, 96, 130 },
                            Text = "Preporučujemo redovne godišnje preglede - zakažite svoj termin na vrijeme.",
                            Title = "Sezonski pregledi"
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 8, 20, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Text = "Vaš nalog je uspješno kreiran. Zakažite svoj prvi termin iz aplikacije.",
                            Title = "Dobrodošli u ClinicNow",
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 8, 21, 10, 30, 0, 0, DateTimeKind.Utc),
                            IsRead = true,
                            ReadAtUtc = new DateTime(2026, 8, 21, 11, 0, 0, 0, DateTimeKind.Utc),
                            Text = "Pacijent Amina Selimović je zakazao/la termin za pregled.",
                            Title = "Novi termin zakazan",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 8, 24, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Text = "Provjerite raspored za sutra - nekoliko termina čeka potvrdu.",
                            Title = "Podsjetnik: nadolazeći termini",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalIdNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonalIdNumber")
                        .IsUnique()
                        .HasFilter("[PersonalIdNumber] IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ferhadija 1, Sarajevo",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            FirstName = "Hana",
                            IsDeleted = false,
                            LastName = "Pacijentić",
                            PersonalIdNumber = "0101990175008",
                            PhoneNumber = "+38761000004",
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            Address = "Zmaja od Bosne 10, Sarajevo",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateOnly(1985, 3, 15),
                            FirstName = "Amar",
                            IsDeleted = false,
                            LastName = "Šehić",
                            PersonalIdNumber = "1503985180012",
                            PhoneNumber = "+38762111222"
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.RevokedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Patient"
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.ScheduleBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("ScheduleBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            EndUtc = new DateTime(2026, 9, 7, 23, 59, 59, 0, DateTimeKind.Utc),
                            Reason = "Godišnji odmor",
                            StartUtc = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Osnovni pregledi i savjetovanja.",
                            Name = "Opća medicina"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bolesti kože, kose i noktiju.",
                            Name = "Dermatologija"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Zdravstvena zaštita djece.",
                            Name = "Pedijatrija"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bolesti srca i krvnih sudova.",
                            Name = "Kardiologija"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Reproduktivno zdravlje žena.",
                            Name = "Ginekologija"
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "administrator@clinicnow.test",
                            FirstName = "Amina",
                            IsActive = true,
                            LastName = "Administratorović",
                            PasswordHash = "$2a$12$J0bbFz7zAKZNCj7tEQSFpeiMgyxOZEcNYLbRAmCDapqmvmJyc3C3i",
                            PhoneNumber = "+38761000001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff@clinicnow.test",
                            FirstName = "Selma",
                            IsActive = true,
                            LastName = "Osoblje",
                            PasswordHash = "$2a$12$J0bbFz7zAKZNCj7tEQSFpeiMgyxOZEcNYLbRAmCDapqmvmJyc3C3i",
                            PhoneNumber = "+38761000002"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor@clinicnow.test",
                            FirstName = "Emir",
                            IsActive = true,
                            LastName = "Doktorović",
                            PasswordHash = "$2a$12$J0bbFz7zAKZNCj7tEQSFpeiMgyxOZEcNYLbRAmCDapqmvmJyc3C3i",
                            PhoneNumber = "+38761000003"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "patient@clinicnow.test",
                            FirstName = "Hana",
                            IsActive = true,
                            LastName = "Pacijentić",
                            PasswordHash = "$2a$12$J0bbFz7zAKZNCj7tEQSFpeiMgyxOZEcNYLbRAmCDapqmvmJyc3C3i",
                            PhoneNumber = "+38761000004"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor2@clinicnow.test",
                            FirstName = "Amila",
                            IsActive = true,
                            LastName = "Kardiologić",
                            PasswordHash = "$2a$12$J0bbFz7zAKZNCj7tEQSFpeiMgyxOZEcNYLbRAmCDapqmvmJyc3C3i",
                            PhoneNumber = "+38761000005"
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.WorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("WorkingHoursEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            DoctorId = 1,
                            EndTime = new TimeOnly(16, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            DoctorId = 1,
                            EndTime = new TimeOnly(16, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3,
                            DoctorId = 1,
                            EndTime = new TimeOnly(16, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4,
                            DoctorId = 1,
                            EndTime = new TimeOnly(16, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            DoctorId = 1,
                            EndTime = new TimeOnly(16, 0, 0),
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            DoctorId = 2,
                            EndTime = new TimeOnly(15, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 3,
                            DoctorId = 2,
                            EndTime = new TimeOnly(15, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 5,
                            DoctorId = 2,
                            EndTime = new TimeOnly(15, 0, 0),
                            StartTime = new TimeOnly(9, 0, 0)
                        });
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Appointment", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicNow.Services.Database.Entities.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicNow.Services.Database.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicNow.Services.Database.Entities.MedicalService", "MedicalService")
                        .WithMany()
                        .HasForeignKey("MedicalServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicNow.Services.Database.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Doctor");

                    b.Navigation("Location");

                    b.Navigation("MedicalService");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.AppointmentAuditLog", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.User", "ActingUser")
                        .WithMany()
                        .HasForeignKey("ActingUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicNow.Services.Database.Entities.Appointment", "Appointment")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActingUser");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Doctor", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicNow.Services.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.DoctorSpecialization", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.Doctor", "Doctor")
                        .WithMany("DoctorSpecializations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicNow.Services.Database.Entities.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Location", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.City", "City")
                        .WithMany("Locations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Notification", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Patient", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.ScheduleBlock", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.Doctor", "Doctor")
                        .WithMany("ScheduleBlocks")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.UserRole", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicNow.Services.Database.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.WorkingHours", b =>
                {
                    b.HasOne("ClinicNow.Services.Database.Entities.Doctor", "Doctor")
                        .WithMany("WorkingHoursList")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Appointment", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.City", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Doctor", b =>
                {
                    b.Navigation("DoctorSpecializations");

                    b.Navigation("ScheduleBlocks");

                    b.Navigation("WorkingHoursList");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ClinicNow.Services.Database.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
